---
apiVersion: v1
kind: Secret
metadata:
  name: walmart-photo-generator-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/WindTurbineInc/walmart-photo-generator-gitops
